### ISSUE TITLE
Output: Missing Academic Year(s) for 62 Entries

### ISSUE THREAD

**Issue by Mbjoerkh** [Vandivier/data-science-practice#13]
See ANDREWS, John J. (Entry 81_5)
ARESHIDZE, Giorgi (89_5) etc. 

I see some of these are institutions with "sub-campus" i.e. University of Texas, Austin. Maybe that's the problem? I will edit the source code for these anyway (replace comma with period)

**Comment by Vandivier** [comment]
great issue and good theory about the root cause. Your solution would be fine. Alternatively we can keep the convention of replacing interior commas with ellipsis (~) during the processing, let me know your preference

**Comment by Mbjoerkh** [comment]
Ellipsis is fine, will do that... Though not all the missing years had that
particular issue, there may be something else going on as well..

**Comment by Mbjoerkh** [comment]
Follow up: Fellows that had 3 sponsors at the same time have the sponsors separated with comma's; see VICTORIUS, Marianne Yvonne (2966_6). Should I use ellipsis there as well?

**Comment by Vandivier** [comment]
ah sry man i meant tilde (~) not ellipsis
