### ISSUE TITLE
Some missing entries

### ISSUE THREAD

**Issue by Mbjoerkh** [Vandivier/data-science-practice#17]
Not sure why, but I'm missing some entries even though they're in your ordered_output and I think I've done everything to keep it up to date? One instance is SEELEY, Luke. Not super urgent, but because I'll have to doublecheck all the cleaning I've done when the output is complete I'll hold off on the cleaning until we find out what's going on..

**Comment by Vandivier** [comment]
SEELEY is within the master revision of EarhartMergedNoBoxNoLines.txt

I imagine the entries you are missing are on some other branch.

In that case you would want at least to merge or even better reset if possible.

**Comment by Vandivier** [comment]
SEELEY is in the master branch ordered-output.csv. Row 1908 or ID 2606_5. Please confirm whether your issue is with master or some other branch.

**Comment by Mbjoerkh** [comment]
The issue is with my branch, but I'm not positive what caused it. There are however, other missing entries on your end such as SEETO, Dewey Quin . How about we look at this at a time convenient to you, maybe this evening? 

I apologize if the learning curve with GIT is causing trouble..

**Comment by Vandivier** [comment]
no worries. yes I think a manual review is in order and this evening should work

**Comment by Mbjoerkh** [comment]
Great - I'm available whenever most convenient for you..

**Comment by Vandivier** [comment]
Per our conversation, we now have 3383 results. We didn't see any particular issue. If you can point to an example person who has an incorrect record, such as wrong # rows or missing altogether, I'll make a change.

An example of a guy who has 3 rows would be interesting.
