### ISSUE TITLE
WEIRDEST THING: Different number of entries every time

### ISSUE THREAD

**Issue by Mbjoerkh** [Vandivier/data-science-practice#19]
Everytime I run the program, the output file contains a different number of entries.. Hah! Recorded it here https://www.useloom.com/share/c1c8360267f04363a2ff2e8731181fbe

Not sure if this happens on your end? 

Big picture: The vast differences on my side leading up to our conversation yesterday was caused by different line endings. This solved that problem "git config --global core.autocrlf true". Could it be the cause of the above?

**Comment by Vandivier** [comment]
issue reproduced and hopefully solved with tip-of-tree, check it out.

My solution was to arbitrarily wait 10s before terminating the process; it's not a guaranteed fix in theory but practically I gave several tries and saw no output changes.

There is a race condition with the stream splitting library I'm using. May not want to use it again in the future.

**Comment by Mbjoerkh** [comment]
I tip my hat to you.. Well done!
